name: aplikasi_guru

description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flip_card: ^0.7.0
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  image_picker: ^1.0.7
  flutter_native_splash: ^2.3.6
  shared_preferences: ^2.2.2
  syncfusion_flutter_datagrid: ^28.2.4
  flutter_launcher_icons: ^0.13.1
  showcaseview: ^4.0.1
  intl: ^0.20.2
  provider: ^6.1.2
  file_picker: ^8.3.1
  excel: ^4.0.6
  flutter_speed_dial: ^7.0.0
  percent_indicator: ^4.2.4
  shimmer: ^3.0.0
  csv: ^6.0.0
  open_file: ^3.5.10
  animated_text_kit: ^4.2.2
  path_provider: ^2.1.5

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo/image.png
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#ffffff"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logoibs.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo/logoibs.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
    - assets/
    - assets/logo/logoibs.png  # adjust filename according to your logo