final List<Map<String, dynamic>> santriData = [
  {
    "studentName": "Ahmad",
    "room": "Ruang 1",
    "className": "10",
    "studentId": "12345",
    "school": "SMA",
    "progressData": [
      {
        'tanggal': '2023-01-01',
        'sesi': '1',
        'surat': 'Al-Fatihah',
        'ayatAwal': '1',
        'ayatAkhir': '7',
        'jumlahBaris': 7,
        'nilai': 90,
        'ustadz': 'Ustadz Ali',
        'halaqoh': 'Takhassus 1',
      },
      {
        'tanggal': '2023-01-02',
        'sesi': '2',
        'surat': 'Al-Baqarah',
        'ayatAwal': '1',
        'ayatAkhir': '5',
        'jumlahBaris': 5,
        'nilai': 85,
        'ustadz': 'Ustadz Budi',
        'halaqoh': 'Takhassus 1',
      },
    ],
  },
  {
    "studentName": "Fatimah",
    "room": "Ruang 2",
    "className": "11",
    "studentId": "67890",
    "school": "SMA",
    "progressData": [
      {
        'tanggal': '2023-01-03',
        'sesi': '1',
        'surat': 'An-Nisa',
        'ayatAwal': '1',
        'ayatAkhir': '10',
        'jumlahBaris': 10,
        'nilai': 95,
        'ustadz': 'Ustadzah Aisyah',
        'halaqoh': 'Takhassus 2',
      },
      {
        'tanggal': '2023-01-04',
        'sesi': '3',
        'surat': 'Al-Maidah',
        'ayatAwal': '1',
        'ayatAkhir': '8',
        'jumlahBaris': 8,
        'nilai': 88,
        'ustadz': 'Ustadzah Zainab',
        'halaqoh': 'Takhassus 2',
      },
    ],
  },
  {
    "studentName": "Yusuf",
    "room": "Ruang 3",
    "className": "12",
    "studentId": "11223",
    "school": "SMA",
    "progressData": [
      {
        'tanggal': '2023-01-05',
        'sesi': '2',
        'surat': 'Yusuf',
        'ayatAwal': '1',
        'ayatAkhir': '11',
        'jumlahBaris': 11,
        'nilai': 92,
        'ustadz': 'Ustadz Umar',
        'halaqoh': 'Takhassus 3',
      },
      {
        'tanggal': '2023-01-06',
        'sesi': '4',
        'surat': 'Al-Kahf',
        'ayatAwal': '1',
        'ayatAkhir': '7',
        'jumlahBaris': 7,
        'nilai': 89,
        'ustadz': 'Ustadz Khalid',
        'halaqoh': 'Takhassus 3',
      },
    ],
  },
  {
    "studentName": "Aisyah",
    "room": "Ruang 4",
    "className": "8",
    "studentId": "33456",
    "school": "SMP",
    "progressData": [
      {
        'tanggal': '2023-01-07',
        'sesi': '1',
        'surat': 'Al-Fil',
        'ayatAwal': '1',
        'ayatAkhir': '5',
        'jumlahBaris': 5,
        'nilai': 93,
        'ustadz': 'Ustadzah Maryam',
        'halaqoh': 'Takhassus 1',
      },
      {
        'tanggal': '2023-01-08',
        'sesi': '2',
        'surat': 'Al-Quraysh',
        'ayatAwal': '1',
        'ayatAkhir': '4',
        'jumlahBaris': 4,
        'nilai': 88,
        'ustadz': 'Ustadzah Hafsah',
        'halaqoh': 'Takhassus 1',
      },
    ],
  },
];
