// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXwb75k4hZdXjP-xEg6coC8t835sGbz_s',
    appId: '1:550149230830:web:5723e645e5f6a7805963ff',
    messagingSenderId: '550149230830',
    projectId: 'backand-apkguru',
    authDomain: 'backand-apkguru.firebaseapp.com',
    storageBucket: 'backand-apkguru.firebasestorage.app',
    measurementId: 'G-859LEKF7Z6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOWJiyrXVZjalPfg8t4TvMQG20uXYCSMc',
    appId: '1:550149230830:android:6795db34ba111dcf5963ff',
    messagingSenderId: '550149230830',
    projectId: 'backand-apkguru',
    storageBucket: 'backand-apkguru.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs8nwVRRRxbKwPuYGsJXfM7cmTld3IlJM',
    appId: '1:550149230830:ios:02a03542a82b5a7d5963ff',
    messagingSenderId: '550149230830',
    projectId: 'backand-apkguru',
    storageBucket: 'backand-apkguru.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiOrtu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs8nwVRRRxbKwPuYGsJXfM7cmTld3IlJM',
    appId: '1:550149230830:ios:02a03542a82b5a7d5963ff',
    messagingSenderId: '550149230830',
    projectId: 'backand-apkguru',
    storageBucket: 'backand-apkguru.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiOrtu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXwb75k4hZdXjP-xEg6coC8t835sGbz_s',
    appId: '1:550149230830:web:bbdac3da4a9a36075963ff',
    messagingSenderId: '550149230830',
    projectId: 'backand-apkguru',
    authDomain: 'backand-apkguru.firebaseapp.com',
    storageBucket: 'backand-apkguru.firebasestorage.app',
    measurementId: 'G-WZHBY1Y30H',
  );
}
